rankdict = {
    "Unranked": "https://i.imgur.com/sB11BIz.png",
    "Copper 1": "https://i.imgur.com/0J0jSWB.jpg",
    "Copper 2": "https://i.imgur.com/eI11lah.jpg",
    "Copper 3": "https://i.imgur.com/6CxJoMn.jpg",
    "Copper 4": "https://i.imgur.com/ehILQ3i.jpg",
    "Copper 5": "https://i.imgur.com/B8NCTyX.png",
    "Bronze 1": "https://i.imgur.com/hmPhPBj.jpg",
    "Bronze 2": "https://i.imgur.com/9AORiNm.jpg",
    "Bronze 3": "https://i.imgur.com/QD5LYD7.jpg",
    "Bronze 4": "https://i.imgur.com/42AC7RD.jpg",
    "Bronze 5": "https://i.imgur.com/TIWCRyO.png",
    "Silver 1": "https://i.imgur.com/KmFpkNc.jpg",
    "Silver 2": "https://i.imgur.com/EswGcx1.jpg",
    "Silver 3": "https://i.imgur.com/m8GToyF.jpg",
    "Silver 4": "https://i.imgur.com/D36ZfuR.jpg",
    "Silver 5": "https://i.imgur.com/PY2p17k.png",
    "Gold 1": "https://i.imgur.com/ffDmiPk.jpg",
    "Gold 2": "https://i.imgur.com/ELbGMc7.jpg",
    "Gold 3": "https://i.imgur.com/B0s1o1h.jpg",
    "Gold 4": "https://i.imgur.com/6Qg6aaH.jpg",
    "Platinum 3": "https://i.imgur.com/qDYwmah.png",
    "Platinum 2": "https://i.imgur.com/CYMO3Er.png",
    "Platinum 1": "https://i.imgur.com/tmcWQ6I.png",
    "Diamond": "https://i.imgur.com/37tSxXm.png",
    "Champion": "https://i.imgur.com/VlnwLGk.png"

}
